FIX: all Document responses have the same schema, regardless of their type
withabound/abound-node pull request #43
Opened 2021-11-21 07:15 UTC by markrmullan

On the first pass, I'd incorrectly assumed that different `Document` response bodies might have different schemas depending on their `type`. This holds true for different `Document` _request bodies_, but it seems like the responses are all normalized.

2021-11-21 07:19 UTC, markrmullan commented on tests/resources/AccountStatementDocuments.spec.ts
> +      const createdDocuments: AboundBulkResponse<Document> =
This could qualify as a semver MAJOR release / breaking changes, as we're altering a public API's return type. Specifically, retiring `AccountStatementDocument` as a valid type def.

2021-11-22 20:14 UTC, bmealhouse requested changes
Add support for `status` and `message` on the Document response.

2021-11-22 20:14 UTC, bmealhouse commented on src/resources/Documents.ts
> +export interface Document {
We also support `status` and `message` (both optional strings) on the Document response.
![Uploading Screen Shot 2021-11-22 at 2.12.19 PM.png…]()

2021-11-23 02:46 UTC, markrmullan commented on src/resources/Documents.ts
> +export interface Document {
Thank you! Could these fields also be added to https://docs.withabound.com/reference/documents?

Added them both as `Readonly`, happy to adjust if that was incorrect

2021-11-23 02:52 UTC, markrmullan commented on src/resources/Documents.ts
> +export interface Document {
here's a corresponding PR for Java: https://github.com/withabound/abound-java/pull/18

2021-11-23 12:37 UTC, bmealhouse commented on src/resources/Documents.ts
> +export interface Document {
> Thank you! Could these fields also be added to https://docs.withabound.com/reference/documents?

Yes, I will update that. Thanks again for pointing that out.

> Added them both as Readonly, happy to adjust if that was incorrect

Should `year` be a `Readonly<string>` as well?

> here's a corresponding PR for Java: withabound/abound-java#18

Approved this PR.

2021-11-29 18:04 UTC, bmealhouse approved these changes

2021-11-30 05:24 UTC, markrmullan commented on src/resources/Documents.ts
> +export interface Document {
oops, sorry about the delayed response here! 🦃 

good call on the readonly `year` — pushing that 👍

2021-11-30 05:28 UTC, merged