FIX: remove 1099-INT as a possible income type
withabound/abound-node pull request #45
Opened 2021-12-14 16:40 UTC by markrmullan

This PR removes 1099-INT as a possible Income type, as it's no longer supported.

2021-12-14 16:46 UTC, bmealhouse requested changes
I think we should keep the examples 1099 related and structure it with `documentType`

2021-12-14 16:46 UTC, bmealhouse commented on README.md
> -  },
Change this to `incomeType: IncomeType.TEN99` with `documentType: DocumentType.TEN99INT`

2021-12-14 16:46 UTC, bmealhouse commented on tests/resources/Incomes.spec.ts
> +            incomeType: IncomeType.PERSONAL,
Change this to `incomeType: IncomeType.TEN99` with `documentType: DocumentType.TEN99INT`

2021-12-14 16:46 UTC, bmealhouse commented on tests/resources/Incomes.spec.ts
> +          incomeType: IncomeType.PERSONAL,
Change this to `incomeType: IncomeType.TEN99`?

2021-12-14 16:52 UTC, markrmullan commented on README.md
> -  },
Oh interesting— `Income.documentType` hasn't even been added to the SDK; assuming it's a relatively new field. Will add this in 👍

2021-12-15 12:14 UTC, bmealhouse requested changes

2021-12-15 12:14 UTC, bmealhouse commented on src/resources/Incomes.ts
> +  documentType?: DocumentType;
Unfortunately, our `documentType` for incomes doesn't completely match up with all of our document `DocumentTypes`. I'm thinking we should create a new enum for this:

```ts
export enum IncomeDocumentType {
  TEN999INT = "1099int",
  TEN99K = "1099k",
  TEN99MISC = "1099misc",
  TEN99NEC = "1099nec",
  SSA1099 = "ssa1099",
}
```

2021-12-15 12:19 UTC, bmealhouse commented on src/resources/Incomes.ts
> +  documentType?: DocumentType;
You can apply the same feedback to the Java SDK.

2021-12-19 17:47 UTC, markrmullan commented on src/resources/Incomes.ts
> +  documentType?: DocumentType;
Perfect— thanks @bmealhouse, applied 🙌

2021-12-20 12:33 UTC, bmealhouse approved these changes
lgtm

2021-12-21 05:03 UTC, merged